# Generated by Django 3.2.16 on 2022-11-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_wishlist', '0002_auto_20221117_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='photos',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='place',
            name='date_visited',
            field=models.DateField(blank=True, null=True),
        ),
    ]
